services:
  db:
    image: postgres:15
    container_name: eskelp-dp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: esklep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esklep-net

volumes:
  postgres_data:

networks:
  esklep-net: